spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # DB Source
    url: jdbc:mysql://springboot-data-database.c5giozjxeuua.ap-northeast-2.rds.amazonaws.com:3306/MyBlog?useSSL=false&allowPublicKeyRetrieval=true
    # DB username
    username: admin
    # DB password
    password: dkemf21518

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

jwt:
  header: Authorization
  #hs256 알고리즘 32비트 이상의 시크릿키 사용
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400


logging.level:
  org.hibernate.SQL: debug

server:
  port: 8081
