#spring:
#  profiles:
#    active: local #dev, real 등
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/testdb
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # DB Source
    url: jdbc:mysql://localhost:3306/secProject?useSSL=false&allowPublicKeyRetrieval=true
    # DB username
    username: root
    # DB password
    password: dkemf21518@

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
#        use_sql_comment: true

jwt:
  header: Authorization
  #hs256 알고리즘 32비트 이상의 시크릿키 사용
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400


logging.level:
  org.hibernate.SQL: debug
