spring:
#  profiles:
#    active: local #dev, real 등
  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        use_sql_comment: true

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace